# Generated by Django 4.2.3 on 2023-07-11 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wallet',
            name='id_hash',
            field=models.CharField(default='', max_length=256),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='wallet',
            name='qr_code',
            field=models.ImageField(default='', max_length=200, upload_to='qrcodes/'),
            preserve_default=False,
        ),
    ]
